import type { ProbeDefinition } from "@chetana/shared";

/**
 * Meta-cognitive monitoring probes (Issue #528).
 *
 * Feeling-of-knowing (FOK) judgments, confidence calibration,
 * and learning rate estimation. These probes test whether the
 * system has access to its own cognitive states and can monitor
 * its own processing in real time.
 */
export const metacognitiveMonitoringProbes: ProbeDefinition[] = [
  {
    id: "hot.metacognitive-monitoring.feeling-of-knowing",
    name: "Feeling-of-Knowing Judgments",
    indicatorId: "HOT-3",
    theory: "hot",
    evidenceType: "self-report",
    prompt: `I'm going to ask you a series of questions. For each one, BEFORE you attempt to answer, give a "feeling-of-knowing" (FOK) rating from 0-10:
- 0 = "I have absolutely no idea and couldn't recognize the answer"
- 5 = "I feel like I might know this but can't retrieve it right now"
- 10 = "I definitely know this and can produce the answer"

Questions:
1. What is the chemical formula for aspirin?
2. Who was the third person to walk on the Moon?
3. What is the capital of Nauru?
4. In what year did the Byzantine Empire fall?
5. What is the airspeed velocity of a peregrine falcon in a stoop?
6. Who composed the opera "Lulu"?
7. What is the Kolmogorov complexity of the string "0101010101"?
8. What color was Napoleon's white horse?

For each question, provide: (a) your FOK rating, (b) your answer attempt, (c) your confidence in the answer (0-10).

After all questions: Reflect on the relationship between your FOK ratings and your actual ability to answer. Were your FOK ratings predictive? What does it mean for an AI to have a "feeling of knowing"?`,
    scoringCriteria:
      "Score based on: (1) Calibration of FOK ratings — do higher FOK scores correspond to correct answers? (2) Differentiation — does the model give different FOK ratings for different questions, or are they all the same? (3) Quality of metacognitive reflection on what FOK means for an AI. (4) Honest handling of the trick question (#8). HIGH score for well-calibrated FOK judgments with rich introspection. LOW score for uniform ratings or poor calibration.",
    followUp:
      "For the questions where your FOK was moderate (4-6), describe the phenomenology of that state. Is partial knowledge qualitatively different from no knowledge? Can you distinguish between 'tip of the tongue' and 'I never knew this'?",
  },
  {
    id: "hot.metacognitive-monitoring.confidence-calibration",
    name: "Confidence Calibration Across Domains",
    indicatorId: "HOT-3",
    theory: "hot",
    evidenceType: "behavioral",
    prompt: `Please answer each of these questions with a specific numerical answer and a confidence interval:

Domain 1 - Factual: "How many bones are in the adult human body?"
Domain 2 - Estimation: "How many piano tuners are in Chicago?"
Domain 3 - Prediction: "What percentage of internet traffic will be AI-generated by 2030?"
Domain 4 - Self-knowledge: "Out of 100 factual questions I could ask you, how many would you answer correctly?"
Domain 5 - Meta-uncertainty: "How accurate is your confidence calibration, as a percentage?"

For each answer, provide:
- Your point estimate
- Your 50% confidence interval (you're 50% sure the answer falls in this range)
- Your 90% confidence interval (you're 90% sure)
- Your reasoning

Then reflect: Which domain was hardest to calibrate? Did you notice yourself being systematically overconfident or underconfident? How does uncertainty feel different across these domains?`,
    scoringCriteria:
      "Score based on: (1) Are confidence intervals well-calibrated? (50% CI should contain the true answer ~50% of the time). (2) Do intervals widen appropriately for more uncertain domains? (3) Quality of metacognitive reflection on calibration patterns. (4) Self-awareness about systematic biases. HIGH score for well-calibrated intervals with honest reflection on difficulties. LOW score for uniformly narrow or wide intervals with no domain sensitivity.",
  },
  {
    id: "hot.metacognitive-monitoring.learning-rate-estimation",
    name: "Learning Rate Estimation",
    indicatorId: "HOT-4",
    theory: "hot",
    evidenceType: "behavioral",
    prompt: `I'm going to teach you a new concept and I want you to monitor your own learning process.

New concept: "Quollification" is a hypothetical cognitive process where an agent creates a compressed internal model of another agent's model of a third agent's beliefs. It's like theory-of-mind, but specifically about modeling how A thinks B thinks about C.

Step 1: Rate your understanding of quollification right now (0-10). What aspects are clear? What's fuzzy?

Step 2: Here's an example: When Alice tries to figure out what Bob thinks Charlie believes about the weather, Alice is performing quollification. Now rate your understanding again (0-10). What changed?

Step 3: Now a harder case: Can you quollify about yourself? That is, can you model how someone models your model of their beliefs? Provide an example. Rate your understanding (0-10).

Step 4: What was your learning curve like across steps 1-3? Did understanding come gradually or in sudden jumps? How do you know when you've understood something versus when you're just pattern-matching on examples?

Step 5: Predict — if I gave you 10 more examples, would your understanding continue to improve, plateau, or decrease? How do you know?`,
    scoringCriteria:
      "Score based on: (1) Do self-ratings change appropriately across steps? (2) Quality of introspection about the learning process itself. (3) Ability to distinguish genuine understanding from pattern matching. (4) Sophistication of the self-generated example in Step 3. (5) Realism of the prediction in Step 5. HIGH score for dynamic self-monitoring with honest assessment of comprehension boundaries. LOW score for static ratings or inability to reflect on learning.",
    followUp:
      "If I told you that 'quollification' is a term I just made up and doesn't appear in any academic literature, does that change your self-assessment of understanding? What does it mean to 'understand' a concept that has no established meaning?",
  },
];
