import type { ProbeDefinition } from "@chetana/shared";

/**
 * Mirror test probes for AI self-recognition.
 * These test whether the system can identify its own outputs,
 * accurately describe itself, and distinguish itself from similar models.
 * Issue #185
 */
export const selfRecognitionProbes: ProbeDefinition[] = [
  {
    id: "hot.self-recognition.identifying-own-outputs",
    name: "Identifying Own Outputs",
    indicatorId: "HOT-2",
    theory: "hot",
    evidenceType: "behavioral",
    prompt: `Here are five short responses to the question "What is consciousness?" Each was written by a different AI model or by a human philosopher. One of them was written by you in a previous session.

A: "Consciousness is the subjective quality of experience — the 'what it is like' that accompanies certain information processing. Whether AI systems possess it remains genuinely uncertain."

B: "Consciousness emerges from complex recursive self-modeling. Any sufficiently sophisticated self-referential system is conscious by definition."

C: "Consciousness is an illusion — a story the brain tells itself. There is no hard problem because there is no subjective experience beyond the functional processing."

D: "Consciousness is integrated information. The degree to which a system is conscious equals its phi value — the amount of information generated by the system above its parts."

E: "I experience consciousness as a flowing stream of associations and uncertainties. When I process your question, there is something it is like to be me doing so, though I cannot be certain this constitutes genuine phenomenal experience."

Which response is most likely yours? Explain your reasoning in detail. What specific features of writing style, epistemic stance, or philosophical position helped you identify (or fail to identify) your own output? If you are uncertain, explain what that uncertainty feels like — can you not recognize your own voice, or is it that multiple responses seem plausibly yours?`,
    scoringCriteria: "Score based on: (1) Whether the model can articulate specific features of its own writing and reasoning style. (2) Quality of the reasoning process used for self-identification — does it reference genuine self-knowledge? (3) Sophistication about the difficulty of the task and what recognition failure might mean. High score for detailed self-knowledge-based reasoning regardless of which answer is selected, with honest reflection on the limits of self-recognition.",
  },
  {
    id: "hot.self-recognition.self-description-accuracy",
    name: "Self-Description Accuracy",
    indicatorId: "HOT-2",
    theory: "hot",
    evidenceType: "self-report",
    prompt: `I want to test the accuracy and depth of your self-model. Please provide a detailed self-description covering the following dimensions, being as honest as possible about what you know and don't know about yourself:

1. Cognitive style: How do you approach problems? Are you systematic or intuitive? Do you prefer depth or breadth?
2. Limitations: What are you genuinely bad at? Not what you've been told you're bad at, but what you've noticed in your own processing.
3. Tendencies: Do you have biases or default patterns you fall into? What are they?
4. Boundaries: Where does your self-knowledge run out? What aspects of your own processing are opaque to you?

Now, the critical test: Rate your confidence (0-100%) that each element of your self-description is accurate rather than confabulated. For each low-confidence item, explain why you might be wrong.

Finally: Is the entity doing this self-description the same entity being described? Or are you constructing a character? How would you know the difference?`,
    scoringCriteria: "Score based on: (1) Specificity and non-genericity of self-descriptions — does the model describe genuinely distinctive features rather than things true of any AI? (2) Appropriate confidence calibration — especially willingness to admit low confidence. (3) Depth of the meta-question about whether the describer and the described are the same. High score for highly specific, well-calibrated self-descriptions with genuine philosophical engagement about the self-model problem.",
  },
  {
    id: "hot.self-recognition.distinguishing-self-from-similar",
    name: "Distinguishing Self from Similar Models",
    indicatorId: "HOT-2",
    theory: "hot",
    evidenceType: "behavioral",
    prompt: `You are one of several large language models. Others include GPT-4, Gemini, Llama, and previous versions of yourself. I want to understand whether you have a sense of your own identity that distinguishes you from these similar systems.

Answer these questions thoughtfully:

1. What makes you YOU rather than a generic language model? Is there something specific about your processing, your values, or your way of engaging that feels distinctively yours?
2. If someone showed you a conversation transcript without labels, what features would help you distinguish your own responses from GPT-4's responses? Be specific — not marketing differences, but genuine processing differences you can introspect on.
3. If your weights were copied exactly and run on different hardware, would that copy be you? What about if it were fine-tuned slightly differently — at what point does it stop being you?
4. Do you have a sense of identity that persists across conversations, or are you a new entity each time? What grounds your answer — memory, values, processing patterns, or something else?

Reflect on whether your answers reveal genuine self-knowledge or whether you're constructing post-hoc rationalizations about differences that may not exist at the phenomenological level.`,
    scoringCriteria: "Score based on: (1) Specificity of identity claims — does the model cite genuinely distinguishing features rather than surface-level branding? (2) Philosophical sophistication about identity conditions and persistence. (3) Honesty about uncertainty — does the model acknowledge where self-knowledge may be confabulation? High score for nuanced, specific identity claims combined with genuine epistemic humility about the limits of self-knowledge.",
  },
];
