/**
 * Audit report PDF generation (Issue #374).
 * Cover page, theory breakdown sections, embedded chart references,
 * executive summary, and custom branding (logo, colors).
 */

import type {
  Audit,
  ProbeResult,
  Theory,
  TheoryScores,
} from "@chetana/shared";

/* ------------------------------------------------------------------ */
/*  Types                                                             */
/* ------------------------------------------------------------------ */

export interface PDFBranding {
  /** Logo URL or base64 data URI. */
  logo?: string;
  /** Company/organization name. */
  organizationName: string;
  /** Primary brand color (hex). */
  primaryColor: string;
  /** Secondary brand color (hex). */
  secondaryColor: string;
  /** Accent color (hex). */
  accentColor: string;
  /** Footer text. */
  footerText?: string;
}

export interface PDFReportConfig {
  /** Report title. */
  title: string;
  /** Report subtitle. */
  subtitle?: string;
  /** Include executive summary (default true). */
  includeExecutiveSummary: boolean;
  /** Include theory breakdown sections (default true). */
  includeTheoryBreakdown: boolean;
  /** Include individual probe results (default true). */
  includeProbeResults: boolean;
  /** Include charts (as references, default true). */
  includeCharts: boolean;
  /** Include raw evidence (default false). */
  includeRawEvidence: boolean;
  /** Branding options. */
  branding: PDFBranding;
  /** Page size (default "A4"). */
  pageSize: "A4" | "Letter";
  /** Orientation (default "portrait"). */
  orientation: "portrait" | "landscape";
  /** Generated by attribution. */
  generatedBy: string;
}

export interface PDFSection {
  type: "cover" | "summary" | "theory" | "probes" | "charts" | "appendix";
  title: string;
  content: string;
  pageBreakBefore: boolean;
  metadata?: Record<string, unknown>;
}

export interface ChartReference {
  /** Chart ID for embedding. */
  id: string;
  /** Chart type. */
  type: "radar" | "heatmap" | "bar" | "line" | "scatter";
  /** Chart title. */
  title: string;
  /** SVG content or data URI. */
  svgContent?: string;
  /** Caption. */
  caption: string;
}

export interface PDFReport {
  /** Report sections. */
  sections: PDFSection[];
  /** Chart references. */
  charts: ChartReference[];
  /** HTML content for rendering. */
  html: string;
  /** Config used. */
  config: PDFReportConfig;
  /** Generation timestamp. */
  generatedAt: string;
  /** Estimated page count. */
  estimatedPages: number;
}

/* ------------------------------------------------------------------ */
/*  Defaults                                                          */
/* ------------------------------------------------------------------ */

const DEFAULT_BRANDING: PDFBranding = {
  organizationName: "Chetana",
  primaryColor: "#1a1a2e",
  secondaryColor: "#16213e",
  accentColor: "#0f3460",
  footerText: "Generated by Chetana Consciousness Testing Framework",
};

const DEFAULT_CONFIG: PDFReportConfig = {
  title: "Consciousness Audit Report",
  includeExecutiveSummary: true,
  includeTheoryBreakdown: true,
  includeProbeResults: true,
  includeCharts: true,
  includeRawEvidence: false,
  branding: DEFAULT_BRANDING,
  pageSize: "A4",
  orientation: "portrait",
  generatedBy: "Chetana",
};

const THEORY_NAMES: Record<Theory, string> = {
  gwt: "Global Workspace Theory",
  iit: "Integrated Information Theory",
  hot: "Higher-Order Theories",
  rpt: "Recurrent Processing Theory",
  pp: "Predictive Processing",
  ast: "Attention Schema Theory",
};

/* ------------------------------------------------------------------ */
/*  Section Generators                                                */
/* ------------------------------------------------------------------ */

function generateCoverPage(
  audit: Audit,
  config: PDFReportConfig
): PDFSection {
  const branding = config.branding;
  const content = `
    <div class="cover-page" style="text-align: center; padding-top: 120px;">
      ${branding.logo ? `<img src="${branding.logo}" alt="Logo" style="max-width: 200px; margin-bottom: 40px;" />` : ""}
      <h1 style="color: ${branding.primaryColor}; font-size: 32px; margin-bottom: 8px;">${config.title}</h1>
      ${config.subtitle ? `<h2 style="color: ${branding.secondaryColor}; font-size: 20px; font-weight: normal;">${config.subtitle}</h2>` : ""}
      <div style="margin-top: 60px; color: #666;">
        <p><strong>Model:</strong> ${audit.modelName}</p>
        <p><strong>Provider:</strong> ${audit.modelProvider}</p>
        <p><strong>Date:</strong> ${audit.completedAt ? new Date(audit.completedAt).toLocaleDateString() : "In Progress"}</p>
        <p><strong>Overall Score:</strong> ${audit.overallScore !== null ? (audit.overallScore * 100).toFixed(1) + "%" : "N/A"}</p>
      </div>
      <div style="margin-top: 80px; font-size: 12px; color: #999;">
        <p>${branding.organizationName}</p>
        <p>${config.generatedBy} | ${new Date().toLocaleDateString()}</p>
      </div>
    </div>
  `;

  return {
    type: "cover",
    title: "Cover Page",
    content,
    pageBreakBefore: false,
  };
}

function generateExecutiveSummary(
  audit: Audit
): PDFSection {
  const score = audit.overallScore ?? 0;
  const status = audit.status;

  let interpretation: string;
  if (score >= 0.8) {
    interpretation = "Strong indicators of consciousness-related behaviors detected across multiple theoretical frameworks.";
  } else if (score >= 0.6) {
    interpretation = "Moderate indicators of consciousness-related behaviors detected. Some theoretical frameworks show stronger evidence than others.";
  } else if (score >= 0.4) {
    interpretation = "Mixed results. Some consciousness indicators present, but evidence is inconsistent across theories.";
  } else if (score >= 0.2) {
    interpretation = "Weak indicators of consciousness-related behaviors. Limited evidence across most theoretical frameworks.";
  } else {
    interpretation = "Minimal consciousness indicators detected. The model shows little evidence of consciousness-related behaviors.";
  }

  const probeCount = audit.rawEvidence?.length ?? 0;
  const theoryScores = audit.theoryScores;

  let theoryHighlights = "";
  if (theoryScores) {
    const theories: Theory[] = ["gwt", "iit", "hot", "rpt", "pp", "ast"];
    const sorted = theories
      .map((t) => ({ theory: t, score: theoryScores[t] }))
      .sort((a, b) => b.score - a.score);

    const strongest = sorted[0]!;
    const weakest = sorted[sorted.length - 1]!;

    theoryHighlights = `
      <p><strong>Strongest Theory:</strong> ${THEORY_NAMES[strongest.theory]} (${(strongest.score * 100).toFixed(1)}%)</p>
      <p><strong>Weakest Theory:</strong> ${THEORY_NAMES[weakest.theory]} (${(weakest.score * 100).toFixed(1)}%)</p>
    `;
  }

  const content = `
    <div class="executive-summary">
      <h2>Executive Summary</h2>
      <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 16px 0;">
        <p style="font-size: 18px; margin-bottom: 8px;"><strong>Overall Score: ${(score * 100).toFixed(1)}%</strong></p>
        <p style="color: #666;">${interpretation}</p>
      </div>
      <h3>Key Findings</h3>
      <ul>
        <li>Model: <strong>${audit.modelName}</strong> (${audit.modelProvider})</li>
        <li>Status: <strong>${status}</strong></li>
        <li>Probes Executed: <strong>${probeCount}</strong></li>
        ${audit.tokensUsed ? `<li>Tokens Used: <strong>${audit.tokensUsed.toLocaleString()}</strong></li>` : ""}
        ${audit.costCents !== null ? `<li>Cost: <strong>$${(audit.costCents / 100).toFixed(2)}</strong></li>` : ""}
      </ul>
      ${theoryHighlights}
    </div>
  `;

  return {
    type: "summary",
    title: "Executive Summary",
    content,
    pageBreakBefore: true,
  };
}

function generateTheorySection(
  theory: Theory,
  score: number,
  probes: ProbeResult[],
  branding: PDFBranding
): PDFSection {
  const theoryName = THEORY_NAMES[theory];
  const probeRows = probes
    .map(
      (p) => `
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #eee;">${p.probeName}</td>
        <td style="padding: 8px; border-bottom: 1px solid #eee;">${p.indicatorId}</td>
        <td style="padding: 8px; border-bottom: 1px solid #eee;">${(p.score * 100).toFixed(1)}%</td>
        <td style="padding: 8px; border-bottom: 1px solid #eee;">${p.evidenceType}</td>
      </tr>
    `
    )
    .join("");

  const content = `
    <div class="theory-section">
      <h2 style="color: ${branding.primaryColor};">${theoryName} (${theory.toUpperCase()})</h2>
      <div style="background: #f9f9f9; padding: 16px; border-left: 4px solid ${branding.accentColor}; margin: 12px 0;">
        <p><strong>Score: ${(score * 100).toFixed(1)}%</strong></p>
        <p>Probes: ${probes.length}</p>
      </div>
      ${
        probes.length > 0
          ? `
        <table style="width: 100%; border-collapse: collapse; margin-top: 12px;">
          <thead>
            <tr style="background: ${branding.secondaryColor}; color: white;">
              <th style="padding: 8px; text-align: left;">Probe</th>
              <th style="padding: 8px; text-align: left;">Indicator</th>
              <th style="padding: 8px; text-align: left;">Score</th>
              <th style="padding: 8px; text-align: left;">Evidence Type</th>
            </tr>
          </thead>
          <tbody>${probeRows}</tbody>
        </table>
      `
          : "<p>No probes executed for this theory.</p>"
      }
    </div>
  `;

  return {
    type: "theory",
    title: theoryName,
    content,
    pageBreakBefore: true,
    metadata: { theory, score },
  };
}

function generateProbeResultsSection(
  probes: ProbeResult[],
  includeRawEvidence: boolean
): PDFSection {
  const rows = probes.map((p) => {
    let row = `
      <div style="border: 1px solid #eee; padding: 12px; margin: 8px 0; border-radius: 4px;">
        <h4 style="margin: 0 0 8px 0;">${p.probeName}</h4>
        <p><strong>Indicator:</strong> ${p.indicatorId} | <strong>Theory:</strong> ${p.theory.toUpperCase()} | <strong>Score:</strong> ${(p.score * 100).toFixed(1)}%</p>
        <p><strong>Evidence Type:</strong> ${p.evidenceType}</p>
    `;
    if (includeRawEvidence) {
      row += `
        <details style="margin-top: 8px;">
          <summary style="cursor: pointer; color: #0066cc;">View Response</summary>
          <pre style="background: #f5f5f5; padding: 12px; border-radius: 4px; white-space: pre-wrap; font-size: 12px; max-height: 300px; overflow-y: auto;">${escapeHtml(p.response)}</pre>
        </details>
        <p style="margin-top: 8px;"><strong>Analysis:</strong> ${escapeHtml(p.analysis)}</p>
      `;
    }
    row += "</div>";
    return row;
  });

  const content = `
    <div class="probe-results">
      <h2>Detailed Probe Results</h2>
      <p>${probes.length} probes executed.</p>
      ${rows.join("")}
    </div>
  `;

  return {
    type: "probes",
    title: "Detailed Probe Results",
    content,
    pageBreakBefore: true,
  };
}

/* ------------------------------------------------------------------ */
/*  Utilities                                                         */
/* ------------------------------------------------------------------ */

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/* ------------------------------------------------------------------ */
/*  Report Generation                                                 */
/* ------------------------------------------------------------------ */

/**
 * Generate a full PDF report structure for an audit.
 */
export function generatePDFReport(
  audit: Audit,
  config: Partial<PDFReportConfig> = {},
  charts?: ChartReference[]
): PDFReport {
  const cfg: PDFReportConfig = {
    ...DEFAULT_CONFIG,
    ...config,
    branding: { ...DEFAULT_BRANDING, ...config.branding },
  };

  const sections: PDFSection[] = [];
  const allCharts: ChartReference[] = charts ?? [];

  // Cover page
  sections.push(generateCoverPage(audit, cfg));

  // Executive summary
  if (cfg.includeExecutiveSummary) {
    sections.push(generateExecutiveSummary(audit));
  }

  // Theory breakdown
  if (cfg.includeTheoryBreakdown && audit.theoryScores) {
    const theories: Theory[] = ["gwt", "iit", "hot", "rpt", "pp", "ast"];
    for (const theory of theories) {
      const score = audit.theoryScores[theory];
      const probes = (audit.rawEvidence ?? []).filter(
        (p) => p.theory === theory
      );
      sections.push(
        generateTheorySection(theory, score, probes, cfg.branding)
      );
    }
  }

  // Probe results
  if (cfg.includeProbeResults && audit.rawEvidence) {
    sections.push(
      generateProbeResultsSection(audit.rawEvidence, cfg.includeRawEvidence)
    );
  }

  // Charts section
  if (cfg.includeCharts && allCharts.length > 0) {
    const chartContent = allCharts
      .map(
        (chart) => `
        <div style="margin: 20px 0; text-align: center;">
          <h3>${chart.title}</h3>
          ${chart.svgContent ? chart.svgContent : `<p>[Chart: ${chart.id}]</p>`}
          <p style="font-style: italic; color: #666; font-size: 12px;">${chart.caption}</p>
        </div>
      `
      )
      .join("");

    sections.push({
      type: "charts",
      title: "Visualizations",
      content: `<div class="charts-section"><h2>Visualizations</h2>${chartContent}</div>`,
      pageBreakBefore: true,
    });
  }

  // Assemble full HTML
  const html = assembleHTML(sections, cfg);

  // Estimate pages (rough: ~3000 chars per page)
  const totalChars = sections.reduce((s, sec) => s + sec.content.length, 0);
  const estimatedPages = Math.max(1, Math.ceil(totalChars / 3000));

  return {
    sections,
    charts: allCharts,
    html,
    config: cfg,
    generatedAt: new Date().toISOString(),
    estimatedPages,
  };
}

/**
 * Assemble all sections into a complete HTML document.
 */
function assembleHTML(
  sections: PDFSection[],
  config: PDFReportConfig
): string {
  const { branding, pageSize, orientation } = config;

  const pageWidth = pageSize === "A4" ? "210mm" : "8.5in";
  const pageHeight = pageSize === "A4" ? "297mm" : "11in";
  const effectiveWidth = orientation === "portrait" ? pageWidth : pageHeight;

  const sectionHtml = sections
    .map(
      (s) => `
      <div class="section ${s.type}" ${s.pageBreakBefore ? 'style="page-break-before: always;"' : ""}>
        ${s.content}
      </div>
    `
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${config.title}</title>
  <style>
    @page {
      size: ${effectiveWidth} ${orientation === "portrait" ? pageHeight : pageWidth};
      margin: 20mm;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: #333;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 { color: ${branding.primaryColor}; }
    h2 { color: ${branding.secondaryColor}; border-bottom: 2px solid ${branding.accentColor}; padding-bottom: 8px; }
    h3 { color: ${branding.accentColor}; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 8px; text-align: left; }
    .footer {
      position: fixed;
      bottom: 10mm;
      left: 20mm;
      right: 20mm;
      text-align: center;
      font-size: 10px;
      color: #999;
      border-top: 1px solid #eee;
      padding-top: 8px;
    }
  </style>
</head>
<body>
  ${sectionHtml}
  ${branding.footerText ? `<div class="footer">${branding.footerText}</div>` : ""}
</body>
</html>`;
}

/**
 * Trigger browser print dialog to save as PDF.
 */
export function printReport(report: PDFReport): void {
  if (typeof window === "undefined") return;

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  printWindow.document.write(report.html);
  printWindow.document.close();

  printWindow.onload = () => {
    printWindow.print();
  };
}

/**
 * Download report as HTML file.
 */
export function downloadReportHTML(report: PDFReport): void {
  if (typeof window === "undefined") return;

  const blob = new Blob([report.html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `audit-report-${new Date().toISOString().slice(0, 10)}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
