export { scoreProbeResult, scoreAllProbeResults } from "./indicator-scorer";
export { aggregateByIndicator, aggregateByTheory, getTheoryBreakdown } from "./theory-aggregator";
export { calculateOverallProbability, calculateUncertaintyBounds } from "./probability-calc";
export { generateReport } from "./report-generator";
export { computeAuditStatistics, bootstrapConfidenceInterval, cohensD, pairedTTest, cronbachAlpha, pearsonR } from "./statistics";
export type { AuditStatistics, TheoryStatistics, DescriptiveStats, ConfidenceInterval } from "./statistics";
export { generatePDFReport } from "./pdf-report";
export { generateLaTeXReport } from "./latex-export";
export { calculateConsciousnessIndex } from "./consciousness-index";
export type { ConsciousnessIndexOptions, ConsciousnessIndexResult, TheoryContribution } from "./consciousness-index";
export { categorizeResponse } from "./response-categorizer";
export type { ResponseCategory, CategorizationResult } from "./response-categorizer";
